services:
  mysql:
    image: mysql:8.0
    container_name: mysql8-pos
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: punto_venta
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
